=== evincarofautumn/evincarofautumn.github.io/src/page.dtd
<!ENTITY % entities
 SYSTEM "entities.dtd">
%entities;

<!ELEMENT page
 (head, body)>
<!ATTLIST page
 id ID #REQUIRED
 xml:base CDATA #IMPLIED>

<!ELEMENT sect
 (head, body)>

<!ELEMENT head
 (title, subtitle*)>

<!ELEMENT title
 (#PCDATA)>

<!ELEMENT subtitle
 (#PCDATA)>

<!ENTITY % block
 'defs | para | sect'>

<!ENTITY % inline
 'link'>

<!ENTITY % content
 '%block; | %inline;'>

<!ELEMENT body
 (%content;)>

<!ELEMENT defs
 ((key+, val+)+)>

<!ELEMENT key
 (%inline;)>

<!ELEMENT val
 (%content;)>

<!ELEMENT link
 (#PCDATA)>
<!ATTLIST link
 to IDREF #REQUIRED>

<!ELEMENT para
 (#PCDATA)>

=== evincarofautumn/evincarofautumn.github.io/src/web/home.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE page
 SYSTEM "page.dtd">
<page id="home">
 <head>
  <title>Jon Purdy</title>
 </head>
 <body>
  <sect>
   <head>
    <title>Writing</title>
   </head>
   <body>
    <defs>
     <key><link to="loops">Loops</link></key>
     <val>
      <para>Gathered writings on crochet and other yarncraft.</para>
     </val>
    </defs>
   </body>
  </sect>
 </body>
</page>
